name: fish_fresh_test
description: "A Flutter app for detecting fish freshness using TensorFlow Lite."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # TensorFlow Lite
  tflite_flutter: ^0.10.4
  # Image handling
  image: ^4.1.3
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  # UI components
  cupertino_icons: ^1.0.2

  # Math utilities for matrix/vector operations
  vector_math: ^2.1.4
  # Permissions
  permission_handler: ^11.3.1
  package_info_plus: ^8.3.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

# Untuk fitur history
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/models/best_float32.tflite
    - assets/images/
    - assets/logo.png
    - assets/icon-launcher.png
  # Platform-specific permissions untuk Android
android:
  permissions:
    - android.permission.CAMERA
    - android.permission.WRITE_EXTERNAL_STORAGE
    - android.permission.READ_EXTERNAL_STORAGE

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon-launcher.png"